from deepClassifier.components.data_ingestion import DataIngestion
from deepClassifier.components.prepare_base_model import PrepareBaseModel
from deepClassifier.components.prepare_callbacks import PrepareCallBackModel
from deepClassifier.components.training import TrainingModel
from deepClassifier.components.evaluation import EvaluationModel